### ISSUE TITLE
ATC booking list - friend alias buggy

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#130]
When trying to add or delete an alias for a person from the ATC booking list, all controllers on that list seem to have that name added - on the booking list. After restarting Qutescoop everything was fine, the alias had not been added to anyone, though.

**Comment by jonaseberle** [comment]
I can't follow completely. How do you add an alias to a booked controller in that list?

We do not have VATSIM IDs of booked controllers (thus they are all "0"), so we should make sure that the "alias" function is not available for them.

**Comment by FlyingFoxVATSIM** [comment]
Moin Jonas,

I think there's something more to it. I just tried to re-create the "feature" and found the following: when I open the booked ATC dialogue with CTRL-F8, select a target-time and then activate "Warp To", **all** controllers **on the map** will show up with the **last** alias name that I have set in one of my previous sessions of Qutescoop.

**Comment by Luca0208** [comment]
> I think there's something more to it. I just tried to re-create the "feature" and found the following: when I open the booked ATC dialogue with CTRL-F8, select a target-time and then activate "Warp To", **all** controllers **on the map** will show up with the **last** alias name that I have set in one of my previous sessions of Qutescoop.

This is due to the same reason Jonas described. While in timewarp mode all controllers have ID "0" for QuteScoop, as such when you originally set the alias of e.g. "MyAlias" QuteScoop saved that ID "0" has alias "MyAlias" and as such will display all booked controllers to have alias "MyAlias".

The vatbook does provide VATSIM IDs (At least some of the time) I'm not sure why these aren't parsed when downloading the booked controller data. That data should probably be parsed and we should prevent setting an alias for controllers with an invalid ID.
Edit: As far as I can see that data should be parsed and stored in the BookedController object, so it must be reset at some point before displaying.
Afaik the first VATSIM ID in use is 800000, so we could probably just prevent setting an alias for all IDs below that?

**Comment by jonaseberle** [comment]
@Luca0208 sounds good. I was not aware that we could get IDs from http://vatbook.euroutepro.com/servinfo.asp - but yes, they are there.
@FlyingFoxVATSIM Andreas, I guess you have now `clients/alias_0 = <alias>` in your settings which gets used for all clients where we failed to get a valid ID. Sorry for that.
I am now off to the mountains for a week :)

**Comment by Luca0208** [comment]
No need to be sorry, I'm working on a PR that'll disallow adding invalid IDs as alias/friend and will contain the required migrations to fix this :)

@jonaseberle when you're back can you take a look at where the ID information is lost? Have a nice vacation :)

**Comment by FlyingFoxVATSIM** [comment]
It's not a deal breaker, I was just surprised when every booked controller had the same Alias :)

Enjoy your trip!

**Comment by jonaseberle** [comment]
I found the position where the Client ID was lost:

During Time Warp we make `BookedController`s to "real" `Controller`s by faking most of their properties in a way that we can show them on the map. We just forgot to transfer the ID. 

Thanks @FlyingFoxVATSIM for reporting this and @Luca0208 for the groundwork and the idea that information gets "lost" somewhere!

As always I'll not merge right away but keep the Pull Request open at least for a day or so to allow for comments.
