### ISSUE TITLE
(local) time in airport information wrong

### ISSUE THREAD

**Issue by diibify** [qutescoop/qutescoop#156]
The wrong time is displayed for "airport information":

Example EDDK: 
Correct time local = 17.34 (UTC+2)
Time shown = 15:34 local (UTC+0)

Version 2.7.0, Windows 11

![EDDK_time](https://user-images.githubusercontent.com/16623471/194356618-f4ae652e-0289-4f19-a0aa-9682cbe7df94.jpg)

**Comment by jonaseberle** [comment]
Not much we can do because actual local times with time zones etc. are non-trivial to do. So this is the "astronomical time, rounded to full hours difference".

We are just estimating by longitude. 
360° = 24h
15° = 1h

Since EDDK is at 7.14 East, it is still in the theoretical UTC+0 (+/-7.5°) region...

Compare with EDLW - that is some miles more to the East and falls into UTC+1....

If that is confusing, we can remove it. In my opinion it does not have a lot of information.

**Comment by diibify** [comment]
If there's not an easy (quick) database source or something, I'd say it confuses people more. But is a great feature itself - the local time is a very cute information.

**Comment by jonaseberle** [comment]
Yes, we won't be able to use real timezones.

Since the basic information (dawn? night?) is also given by our sun lighting, I'll remove it.
