### ISSUE TITLE
Navdata source: switch to X-Plane 11/12

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#17]
The link from the QuteScoop settings https://data.x-plane.com redirects to https://developer.x-plane.com/docs/data-development-documentation/ which describes the file structure but does not have downloads any more.

But the data is Open Source licensed and somebody put them on Github: https://github.com/mcantsin/x-plane-navdata 

For QuteScoop to process it, put all the .dat files in a subfolder "default data" and point QuteScoop to the parent directory.

Yet the data is very outdated and probably not useful any more. Any ideas on how to proceed are welcome.

**Comment by dneuge** [comment]
If users have a Navigraph subscription they can set up an additional "X-Plane" entry for QuteScoop; I don't have NavDataPro but I would expect it works the same. I have been using current navdata like this for a long time. It's just important that the folder structure matches QuteScoop's expectation, otherwise QuteScoop won't find the files - maybe folder selection/detection could be reworked to make that easier and less confusing for users (no more "default data" subdirectory).

Not sure what to do about default navdata for QuteScoop though if users don't have any such subscription. I don't think there's any free data source.

**Comment by droesen** [comment]
BTW, is QS compatible with current X-Plane navdata format? I for one keep installing two navdata sets (Navigraph) - one "X-Plane 11.50 (and above)" for X-Plane itself, and one legacy "X-Plane 10 (10.30+)" to install into QuteScoop directory for QS' use. Would be nice if we could adapt QS to read X-Plane 11.50 navdata and get away with one update for X-Plane users. Given how Navigraph reacted regarding X-Plane 11.50, I wonder when they're going to throw out XP10 dataset anyway...

**Comment by jonaseberle** [comment]
I just tried yesterday and I also found it is not compatible with v11 - the format changed quite a lot.

**Comment by FlyingFoxVATSIM** [comment]
> I just tried yesterday and I also found it is not compatible with v11 - the format changed quite a lot.
Yes, you have to use X-Plane 10 NavData for Qutescoop. As Daniel wrote, it will be just a question of time until NavData for XP10 won't be available anymore.

**Comment by jonaseberle** [comment]
Data file format definition:
https://developer.x-plane.com/article/navdata-in-x-plane-11/

**Comment by jonaseberle** [comment]
I've just simplified the settings (still X-Plane 10) a bit:
![image](https://user-images.githubusercontent.com/1678001/152438376-555f10d2-bacc-4b0e-aa4a-faf4590949b3.png)
(It expected the actual data to be in a subfolder `default data` of the selected folder. Now it is the actual folder).

And I put it into a release ;) https://github.com/qutescoop/qutescoop/releases/tag/v2.3.0

**Comment by droesen** [comment]
Looks like X-Plane 12 will have yet some more modifications to the data format:

https://developer.x-plane.com/article/navdata-in-x-plane-11/#Global_Data_Formats
