### ISSUE TITLE
Offer alternate ATC ground station symbology

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#243]
I myself have a really hard time (read: fail constantly) remembering what kind of circle/star/whatever symbology depicts which kind of ATC ground station (TWR/GND/DEL). This makes it hard for me to get a quick overview and I always have to mouse-over airports to check what's really offered. The Good Old ServInfo used icons for that, a small tower and airstrip cross:

![image](https://github.com/qutescoop/qutescoop/assets/63562075/d0dc7f42-2201-4f0b-9a7b-1abcd1c5f52b)

(sorry, didn't find a better screenshot anymore)

Could we add such icons as an option? Perhaps with a small FPL symbol for DEL stations? ServInfo combined DEL with GND, which would be another way to go.

**Comment by jonaseberle** [comment]
Noted. 

This is our current DEL+GND+TWR+APP (+CTR) symbology:
![image](https://github.com/qutescoop/qutescoop/assets/1678001/68162810-b54b-413f-bac4-7a49f4e66967)
I got pretty much used to it.

Floating icons (in the 2D space, with fixed sizes) is something I have never tried. Easier would be a texture in the 3D space but that would scale with the zoom. We can see.

**Comment by jonaseberle** [comment]
Here's a sneak peek of what I'm working on. 

I am about to make pilot/airport labels contents configurable for the user. The user will be able to add a `{controllers}` place holder to the label that will output "D,G,T,A" etc.

![image](https://github.com/qutescoop/qutescoop/assets/1678001/bd3cf1bc-dcf7-421a-8e11-e04547847e14)

As said, icons are hard but they might come at a later point. Let me know what you think.

**Comment by jonaseberle** [comment]
With the upcoming v3.0.0 the label system allows some freedom to use Unicode symbols (emoticons) in labels.

We make use of it for these things already:
![image](https://github.com/qutescoop/qutescoop/assets/1678001/9dde5d23-94d4-4569-905f-7175f9011a3a)
![image](https://github.com/qutescoop/qutescoop/assets/1678001/7e610765-2cfb-4103-9276-b8951ec7cc10)

I have added label placeholders for DEL/GND/TWR/APP so the user can use any emoticon/Unicode symbol supported by the font. For example:
![image](https://github.com/qutescoop/qutescoop/assets/1678001/81d68b68-2471-427a-9260-e9b13e04d17d)

So with v3.0.0 one could do that:
![image](https://github.com/qutescoop/qutescoop/assets/1678001/969ca1b4-fe31-4fd6-85e4-f4d4abcfe8bb)

It's currently not possible to use a bigger font size for parts of the label. And I can't promise if that will ever come because it is considerable work.

**Comment by jonaseberle** [comment]
Huhu, @droesen. How do you read?

**Comment by droesen** [comment]
5/5, standby, call you back :-D

**Comment by jonaseberle** [comment]
Ok, if you have time can you have a look at https://github.com/qutescoop/qutescoop/releases/tag/v3.0.0-rc.3 ?

**Comment by droesen** [comment]
Great work. Extremely flexible now, congrats and muchas gracias! Mea culpa for taking so much time to review that RC.

For me personally, the {gnd} etc. placeholders using T/G/D while disabling the graphics for GND/DEL come closest to what I'd really like to see (well-visible icons). I'll see wether I get used to it over time and lose my desire for icons. :-)

I'll leave more detailled feedback in seperate new issues.

Thanks Jonas!
