### ISSUE TITLE
Qutescope does not depict VATSIM data since 06 april. How to fix it?

### ISSUE THREAD

**Issue by Alexiyi** [qutescoop/qutescoop#32]

**Comment by FlyingFoxVATSIM** [comment]
It is being worked on. In the meantime use Daniel's proxy tool to inject ATC and pilot data into Qutescoop

https://github.com/dneuge/legacy-status-proxy-vatsim

**Comment by Alexiyi** [comment]
Ah. I don't understand how to set it. Can you please explane which files I must download to make it work? I would really apprecite!

**Comment by FlyingFoxVATSIM** [comment]
> 
> 
> Ah. I don't understand how to set it. Can you please explane which files I must download to make it work? I would really apprecite!

It is really easy. Just download from the "Releases" on the right side. Then follow the text instructions on the Github page.

https://github.com/dneuge/legacy-status-proxy-vatsim/blob/master/docs/manual.md

**Comment by Alexiyi** [comment]
Thanks!

**Comment by Alexiyi** [comment]
Another problem. Planes' and ATCs' lables do not depict

**Comment by jonaseberle** [comment]
Please always report which version you are using.

The latest git-Version also supports the changed Vatsim feed fornat but i am not able to provide compiled windows versions since I myself am not using Windows and thus cannot test. The only thing I know that our last releases https://github.com/qutescoop/qutescoop/releases did not work. 

Supposedly working Mac and Linux versions of currently unreleased versions are here https://github.com/qutescoop/qutescoop/actions (downloads are under "artefacts").

**Comment by Alexiyi** [comment]
Oh sorry, I use Windows 10 the latest version, and QuteScope 2.1.13.1beta

**Comment by jonaseberle** [comment]
Labels depend highly on the QuteScoop graphics settings. If your problem persists, please open a new issue with version number and your graphics settings.

I am closing here since the data feed thingy is fixed already. Lets track progress on a Windows release here https://github.com/qutescoop/qutescoop/issues/15
